spring:
  datasource:
    username: root
    url: jdbc:mysql://140.143.148.16:3306/guli-sms
    driver-class-name: com.mysql.jdbc.Driver
    password: root

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: gulimall-coupon



mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 8010


